[package]
name = "LexAi_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.10.0"
ic-cdk-macros = "0.7.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
candid = "0.9"  # Required for CandidType
once_cell = "1.18.0"
