[package]
name = "LexAi_backend"
version = "0.1.0"
edition = "2021"



[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.14"
ic-cdk = "0.18.3"
serde = "1.0.219"
serde_json = "1.0.140"
sha2 = "0.10"
hex = "0.4"
ic-stable-structures = "0.6.5"

