[package]
name = "LexAi_backend"
version = "0.1.0"
edition = "2021"



[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.18"
candid = "0.10"
ic-cdk-macros = "0.18.5"
serde = { version = "1.0", features = ["derive"] }

